name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  cloud_firestore: ^0.14.4
  http: ^0.12.2
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/sva.jpg
    - assets/scan.jpg
    - assets/profile.jpg
    - assets/user.png
    - assets/News.png
    - assets/bell.png
    #- assets/alucard.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf